### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by zouuxx** [Al3XKOoL/android_device_wiko_rainbow-WIP#26] opened 2015-09-24 13:25 UTC
When Typing Sometimes It Lags
It Become Slow To Type 

Buggy

**Comment by zouuxx** [comment] 2015-09-26 06:20
Any Ideas What Cause This Issue ?

No Enough Ram ?

**Comment by Al3XKOoL** [comment] 2015-10-25 11:06
I can't reproduce it in the lastest build.
Close the issue for now.

**Closed as completed by Al3XKOoL** 2015-10-25 11:06 UTC
