### ISSUE TITLE
USSD

### ISSUE THREAD

**Issue by kosqqqa** [Al3XKOoL/android_device_wiko_rainbow-WIP#32] opened 2015-10-02 11:49 UTC
USSD Check don't work.Do You fix it?

**Comment by Al3XKOoL** [comment] 2015-10-02 14:59
We are working on fix it.

**Comment by kosqqqa** [comment] 2015-10-16 14:16
Ok. It has not yet been fixed?

**Comment by Al3XKOoL** [comment] 2015-10-17 20:21
This is a weird problem, for some carriers is working... and ril log is the same for both. 

I can't found the cause for now.

**Comment by anomalchik** [comment] 2015-10-25 13:20
https://github.com/anomalchik/alps_packages_services_Telephony/blob/master/src/com/mediatek/phone/UssdAlertActivity.java

it can with something to help you?
it is required to build mediatek plugin manager.

**Comment by anomalchik** [comment] 2015-10-25 13:30
I want to add that ussd works, but not completely. Do not operate only simple notification.
Notifications with the choice of work
![2015-10-25 16-29-06](https://cloud.githubusercontent.com/assets/3417567/10715843/b16bc7f6-7b35-11e5-8526-ec179fb3b51b.png)

**Comment by prshkr07** [comment] 2015-11-27 08:31
After switching to a lot of different carriers it appears that only interactive (which contains input field) ussd messages work.
Interactive/working ussd: 
![screenshot_2015-11-26-22-34-08](https://cloud.githubusercontent.com/assets/9952596/11436873/d62c6b34-950e-11e5-8645-cd339272fbaa.png)
Non-interactive/not working ussd: 
![screenshot_2015-11-09-12-20-58](https://cloud.githubusercontent.com/assets/9952596/11436937/5396f972-950f-11e5-9b45-82da41814474.png)

**Comment by aniruddha-adhikary** [comment] 2015-12-20 03:34
I have some heads up on this. The GsmMmiCode implementation returns null for USSD responses without any input field/

**Comment by aniruddha-adhikary** [comment] 2015-12-20 08:59
@Al3XKOoL check this: https://github.com/aniruddha-adhikary/android_frameworks_opt_telephony_mtk/commit/800dd27619a25e3e579732dcc0cf1f6a685c54cf

**Comment by prshkr07** [comment] 2015-12-20 16:04
thanks @aniruddha-adhikary  you finally fixed this bug.

**Comment by Al3XKOoL** [comment] 2015-12-20 16:06
Hi @aniruddha-adhikary 

I already look at these changes, testing soon.
Ty!

**Comment by Al3XKOoL** [comment] 2015-12-21 20:17
All working.
@aniruddha-adhikary thanks and nice find ;)

USSD fixed in the next build.

**Closed as completed by Al3XKOoL** 2015-12-21 20:17 UTC
