### ISSUE TITLE
Facebook messenger bug [VoIP Calls]

### ISSUE THREAD

**Issue by mrdarkus** [Al3XKOoL/android_device_wiko_rainbow-WIP#9] opened 2015-08-28 12:50 UTC
When i try to make a call in facebook messenger it fails i hope you will fix it

**Comment by Al3XKOoL** [comment] 2015-08-29 15:40
Voip call isn't working for now.

**Comment by Klexer** [comment] 2015-09-27 12:23
I found out VoIP issues are caused by microphone. When using FRITZ!App Fon, I can fix it by Settings / Advanced / Alternative Microphone. Microphone bug #22 is closed. Shouldn't FB messenger bug #9 also be fixed now?

**Comment by Al3XKOoL** [comment] 2015-09-27 15:02
Sorry i miss it.
Fixed in the next release

**Closed as completed by Al3XKOoL** 2015-09-27 15:02 UTC
Labels: bug
